services:
  nginx:
    image: nginx:1.25.4
    container_name: nginx
    restart: always
    volumes:
      - "./elk:/etc/nginx/conf.d/default.conf"
      - "./.htpasswd:/etc/nginx/.htpasswd"
    ports:
      - "80:80"
    networks:
      - default

      
      
      
      
